# Deep Learning with PyTorch

## Tensors
*Tensors* represent
* *multilinear maps* between vector spaces (mathematics)
* generic *n-dimensional arrays* (computer science)

In [1]:
import numpy as np
import torch

# Create an uninitialized 3x2 tensor of 32-bit floats
a = torch.FloatTensor(3, 2)
a

tensor([[1.3556e-19, 3.0097e+29],
        [7.1853e+22, 4.5145e+27],
        [1.8040e+28, 1.5769e-19]])

In [2]:
# Initialize the tensor (in-place) with zeros
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

There are two types of methods in the PyTorch API:
* Functional ones that return transformed copies have standard names like `some_function()`
* In-place mutating operations will have a trailing underscore in their name, e.g. `some_function_()`

In [3]:
# Create a tensor from a standard collection
torch.FloatTensor([[1, 2, 3], [3, 2, 1]])

tensor([[1., 2., 3.],
        [3., 2., 1.]])

In [4]:
n = np.zeros(shape=(3, 2))
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
# Create a tensor from a numpy ndarray
b = torch.tensor(n)
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [8]:
# Change the numpy array to 64-bit float
#  - This translates to the tensor
n = np.zeros(shape=(3, 2), dtype=np.float32)
torch.tensor(n)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [9]:
# Alternatively specify a PyTorch dtype
n = np.zeros(shape=(3, 2))
torch.tensor(n, dtype=torch.float32)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [12]:
# Scalar tensors can be results of some aggregations
s = a.sum()
s

tensor(6)

In [13]:
# There's a convenient method to access the value of a scalar tensor
s.item()

6

In [14]:
torch.tensor(42)

tensor(42)

### Tensor Operations
Each tensor has associated `device` where the computation takes place. The options are
* `cpu` - computation takes place on the CPU
* `cuda` or `cuda:<index>` - computation takes place on the GPU (with a device id `<index>`)

In [18]:
# Determine computation device based on CUDA availability
device = "cuda" if torch.cuda.is_available() else "cpu"

a = torch.FloatTensor([2, 3])

# Move the tensor to GPU (if there's CUDA available)
a = a.to(device)
a

tensor([2., 3.])

In [19]:
a.device

device(type='cpu')

### Tensors and Gradients
Each tensor has following info related to automatic gradient computation:
* `grad` is a property holding computed gradients (tensor of the same shape)
* `is_leaf` is true if the tensor was constructed by a user and false if it's a result of a computation
* `requires_grad` is true if the tensor requires gradients to be computed

In [23]:
# Define some tensors
#  - The first one requires gradients to be computed
v1 = torch.tensor([1.0, 1.0], requires_grad=True)
v2 = torch.tensor([2.0, 2.0])

# Define a computational graph on these tensors
#  - Notice: Result contains a function coputing the gradient.
v_sum = v1 + v2
v_res = (v_sum * 2).sum()
v_res

tensor(12., grad_fn=<SumBackward0>)

In [24]:
v1.is_leaf, v2.is_leaf

(True, True)

In [25]:
v_sum.is_leaf, v_res.is_leaf

(False, False)

In [27]:
v1.requires_grad, v2.requires_grad

(True, False)

In [28]:
v_sum.requires_grad, v_res.requires_grad

(True, True)

In [29]:
# Calculate the gradients of our graph
v_res.backward()

# Show backpropagated gradients in v1
v1.grad

tensor([2., 2.])

In [30]:
# v2 does not require any gradients so there's nothing
v2.grad

## Neural Network Building Blocks

In [32]:
import torch.nn as nn  # noqa

# Construct a 2-to-5 dense layer with an implicit bias
#  - Note: Weights of this layer are randomly initialized.
dense = nn.Linear(2, 5)

# Each PyTorch NN module acts as a callable
inputs = torch.FloatTensor([1, 2])
dense(inputs)

tensor([-1.1789, -0.4192, -0.8343, -1.2979, -0.6996], grad_fn=<AddBackward0>)

Some important methods from PyTorch API:
* `parameters()` returns an iterable of all trainable variables (those that require gradients)
* `zero_grad()` initializes all gradients to zero
* `to(device)` moves the computation to a device
* `state_dict()` exports all weights to a dictionary for model serialization
* `load_state_dict()` oppisite of the previous which imports weights

In [33]:
# Build a sequential model with
#  - Three dense layers with ReLU activations
#  - A dropout layer
#  - And a softmax output over the feature dimension
model = nn.Sequential(
    nn.Linear(2, 5),
    nn.ReLU(),
    nn.Linear(5, 20),
    nn.ReLU(),
    nn.Linear(20, 10),
    nn.ReLU(),
    nn.Dropout(p=0.3),
    nn.Softmax(dim=1),
)

model

Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=10, bias=True)
  (5): ReLU()
  (6): Dropout(p=0.3, inplace=False)
  (7): Softmax(dim=1)
)

In [34]:
# Feed an input tensor through our sequential model
#  - There's single instance in the input batch
model(torch.FloatTensor([[1, 2]]))

tensor([[0.0937, 0.1025, 0.0937, 0.1092, 0.0937, 0.0937, 0.1323, 0.0937, 0.0937,
         0.0937]], grad_fn=<SoftmaxBackward>)